// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CloseWindow 关闭窗口
 */
export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(1836492860);
}

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(1411160069, name);
}

/**
 * MaximizeWindow 最大化窗口
 */
export function MaximizeWindow(): $CancellablePromise<void> {
    return $Call.ByID(376863634);
}

/**
 * MinimizeWindow 最小化窗口
 */
export function MinimizeWindow(): $CancellablePromise<void> {
    return $Call.ByID(2935093088);
}
